[project]
name = "ecommerce-sales-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "om panchal", email = "panchalom470@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[project.scripts]
ecommerce-sales-analysis = "ecommerce_sales_analysis:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
